### ISSUE TITLE
[Issue] Low quality video when a livestream starts

### ISSUE THREAD

**Issue by ezefranca** [bambuser/bambuser-livevideoshoppingplayer-sdk-ios#12]
Hello everyone, 

We have been getting some issues (even with demo app) about the video quality. Sometimes the video starts with a very low quality and took some time to get better. I tested this on devices and simulators with different quality of internet and looks like it's not a network issue but someway the video is rendered.

![image](https://user-images.githubusercontent.com/3648336/165954791-9c5fee20-1950-4f75-a9b4-1acabe9ff511.png)

**Comment by ken-bam** [comment]
Per your description it sounds like quality switching is being a bit extra picky. About how long does it take before it steps up in quality? 

Seen any difference in behaviour between iOS versions?

By rendering in this context. Do you mean the rendering of the videon frames on screen or that that rendering of other UI elements is affecting?

**Comment by ezefranca** [comment]
Hello @ken-bam . It's happen during ~10 to ~40 seconds. I don't have a list of which iOS version and device, but we tested in different devices (I will note and report that for future). Rendering in this context is the video. The other elements works fine (buttons, controls etc).

**Comment by ken-bam** [comment]
Hi,

Ok, our playlists has as first entry 360 x 640(if portrait) and on a good stable network it usually pretty fast jumps up to highest quality. In your case it seems that it for some reason decides to step down to 180 x 320(our lowest) before it works its way up to the highest. 

It does not however get stuck on low quality for a long time?

**Comment by ken-bam** [comment]
We have increased the bitrate for the lowest rendition a bit in the hls ladder. So at occasions when the player for whatever reasons decides to drop down to the lowest rendition(apples hls players since iOS 15 are very sensitive to network delays) it does not look as bad anymore.
