### ISSUE TITLE
[Issue] T&Cs link is not clickable

### ISSUE THREAD

**Issue by heldernunesff** [bambuser/bambuser-livevideoshoppingplayer-sdk-ios#13]
Hello everyone 👋

I hope you find you well

We have found some issues on when o open the chat on the live stream and the Terms and Conditions link is not opening. Can you please help with this issue?
![image (2)](https://user-images.githubusercontent.com/110619683/183052980-25da4dc0-3d65-420f-b788-5454ad5faf94.png)

**Comment by ken-bam** [comment]
Without looking at the code base. I would assume this is due to that the sdk does not handle navigation at the moment, but I might be wrong.

A solution you are looking for is perhaps some event or similar, telling you "hey, the user clicked this link www.examplelink.com" then you can yourself validate the url and open it in a web view or browser?

**Comment by heldernunesff** [comment]
Hello everyone 😊
Thank you for sharing. I am just make sure that we’re getting it right: for us to support the handling of the navigation when the user clicks through the privacy policy, that would require not only development on our side but also on yours and further the deployment of an an updated SDK version?
If we are to proceed this way, what would the timeline be for this on your side?

**Comment by ken-bam** [comment]
Yes my interpretation is that it would need a development effort from our side and a release of a new SDK version and most likely an effort as well from the implementer once the SDK is updated. I currently have no timeline estimate.

**Comment by pontusj-bambuser** [comment]
Hello @heldernunesff! This is now fixed with version 0.8.1. The new `openExternalUrl ` event contains an URL that you have to handle and open manually from your side.
