### ISSUE TITLE
[Issue] - Links through chat cannot be clicked through

### ISSUE THREAD

**Issue by heldernunesff** [bambuser/bambuser-livevideoshoppingplayer-sdk-ios#14]
Hello everyone 👋

I hope you find you well.

We have a issue when the user sees a link on the chat (that’s been sent by our Content Moderator) they see the URL but it’s not hyperlinked even, so it’s not tappable.

Can you help us with this issue

Than you in advance

**Comment by ken-bam** [comment]
To make it clickable you need to add "https://" infront of the URL, see https://bambuser.com/docs/one-to-many/faq, but I would assume it would still not work in the sdk due to reasons mentioned in #13

**Comment by pontusj-bambuser** [comment]
Hello @heldernunesff! This is now fixed with version 0.8.1. The new `openExternalUrl ` event contains an URL that you have to handle and open manually from your side.
