### ISSUE TITLE
Can't import framework with Xcode 14.3

### ISSUE THREAD

**Issue by andredp** [bambuser/bambuser-livevideoshoppingplayer-sdk-ios#18]
Hey,

We’re adapting the Farfetch App to be compatible with the latest iOS Development toolchain (Xcode 14.3) and we’re having trouble importing Bambuser’s framework due to the following error:

> **Failed to build module 'BambuserLiveVideoShoppingPlayer'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)', while this compiler is 'Apple Swift version 5.8 (swiftlang-5.8.0.124.1 clang-1403.0.22.11.100)'). Please select a toolchain which matches the SDK.**

Can you provide updated binaries compatible with Xcode 14.3?

⚠️ **Note:** Since 14.3 is still beta, it's worth trying to compile it with 14.2 first to check if it's enough for compatibility purposes.

Thanks

**Comment by andredp** [comment]
@ken-bam , noticed you uploaded a new release dealing with this. Thanks! We'll test it and let you know our findings.

**Comment by andredp** [comment]
We just tested, and the last release fixes this. Thanks!

**Comment by ken-bam** [comment]
Nice! Thanks for the fast feedback!
