### ISSUE TITLE
Feedback from Matas

### ISSUE THREAD

**Issue by JesperBerthelsen** [bambuser/bambuser-livevideoshoppingplayer-sdk-ios#6]
As agreed I'll post the feedback here:

- To integrate this library we need to update our minimum iOS version to iOS 13 which is currently iOS 11.4. This will exclude 1,53 percent of our users. We need to discuss internally if this is okay for us or not 😊
 

- We are unable to remove the chat, products and ”…” buttons in “small mode”
 

![image](https://user-images.githubusercontent.com/101191695/157247140-9a25bfdb-b893-493c-b616-874601d86231.png)
 

 

- We are unable to find anything related to mute/unmute audio which we need in “small” mode.
 

- The idea of just showing the full video in a smaller view, does not perform well in the app, and we want to avoid users seeing a loading spinner when video starts. We want it to play immediately, so a video preview/thumbnail solution could be really cool. I know Mathilde also want this functionality on [matas.dk](http://matas.dk/),

**Comment by ken-bam** [comment]
Hi @JesperBerthelsen 

Can you perhaps split up these in separate issues. It is easier for both of us to deal with them one by one.

Regards

**Comment by ken-bam** [comment]
I reply to the feedback now in this thread. But it would be nice if you could create separate issues for each of them.

1) Any particular reason you need support for iOS 11.4? iPhone 5 and 5C are limited to iOS 10.3.x and iPhone 5S, 6 and 6 Plus are limited to 12.5.5. I think there is no device that stops at iOS 11.4?

**Comment by ken-bam** [comment]
2) If you want to toggle between hiding and showing the UI overlay you can do that by:

Hiding:
```
playerView.invoke(.hideUI, completion: {_ in
// do stuff
})
```
showing:
```
playerView.invoke(.showUI, completion: {_ in
// do stuff
})
```

and if you want to hide it right from the start of playback you could do something like this in your event handler:

```
if eventInfo.event == .playerDidBecomeReady {
  self.playerView.invoke(.hideUI, completion:  {_ in
    // do stuff
  })
}
```

In a coming release(probably already in the next) we are adding to the .hideUI call the possibility to specify which parts of the UI to hide.

**Comment by ken-bam** [comment]
3. Oh bummer 😞  unfortunately there is no interface to explicit toggle mute on/off. But, that should be pretty straight forward to implement. We will add a task for that.

**Comment by ken-bam** [comment]
4. Yeah there is delay in the beginning when metadata is being fetched and initial buffering is taking place. You are perhaps looking for some sort of `load` call to do prefetching "off-screen" and then start actual playback with a `play` call? Another way would be as you suggested to show a thumbnail/overlay/preview while loading and then hide it based on an `playing` event. the. But, we will look into ways to improve the initial flow and user experience.

**Comment by ken-bam** [comment]
Thanx for your feedback, much appreciated!

**Comment by ken-bam** [comment]
I close this one now when we have separate issues for each of these. Easier to track progress per issue.
