### ISSUE TITLE
Matas feedback - Minimum OS version iOS 13

### ISSUE THREAD

**Issue by JesperBerthelsen** [bambuser/bambuser-livevideoshoppingplayer-sdk-ios#7]
To integrate this library we need to update our minimum iOS version to iOS 13 which is currently iOS 11.4. This will exclude 1,53 percent of our users. We need to discuss internally if this is okay for us or not 😊

**Comment by JesperBerthelsen** [comment]
You question:
Any particular reason you need support for iOS 11.4? iPhone 5 and 5C are limited to iOS 10.3.x and iPhone 5S, 6 and 6 Plus are limited to 12.5.5. I think there is no device that stops at iOS 11.4?

**Comment by ken-bam** [comment]
OK, so you want to use the minimun iOS version supported by you development enviromnet.

I would have bump to 12.0 at once since you have already excluded  iPhone 5 and 5C and older phones with iOS 11.4 and any newer supports iOS 12 or newer.

**Comment by JesperBerthelsen** [comment]
You're right. 12.0 would also be fine.

**Comment by ken-bam** [comment]
Okay, but that is fine by us. We can add support for iOS12.0.

**Comment by JesperBerthelsen** [comment]
Great :-)

**Comment by ken-bam** [comment]
Hi,

The new release 0.8 has support for iOS12. Try it out and pleas let us know if you run into any troubles.

**Comment by JesperBerthelsen** [comment]
Thanks

**Comment by ken-bam** [comment]
I will close this issue now. Support for iOS12 was implemented in the 0.8 release.
